//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balloon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Balloon()
        {
            this.Shippers = new HashSet<Shipper>();
        }
    
        public int BalloonID { get; set; }
        public string SerialNo { get; set; }
        public string BalloonTitle { get; set; }
        public string Description { get; set; }
        public int GenreID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public Nullable<System.DateTime> ProdDate { get; set; }
        public int DistributorsID { get; set; }
        public string BalloonImg { get; set; }
        public bool IsCategoryFeature { get; set; }
        public int BalloonStatusID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public int ManufactID { get; set; }
        public Nullable<int> AccessID { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual BalloonStatu BalloonStatu { get; set; }
        public virtual Distributor Distributor { get; set; }
        public virtual Seasonal Seasonal { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipper> Shippers { get; set; }
        public virtual BalloonType BalloonType { get; set; }
    }
}
