//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string PayID { get; set; }
        public bool isCash { get; set; }
        public bool isCheck { get; set; }
        public bool isCard { get; set; }
        public string CheckNbr { get; set; }
        public string CardNbr { get; set; }
    }
}
