//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public int ShipID { get; set; }
        public string ShipVIA { get; set; }
        public string FIrstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public int StateID { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public bool Residential { get; set; }
        public bool Commercial { get; set; }
        public string Notes { get; set; }
        public Nullable<int> BalloonID { get; set; }
    
        public virtual Balloon Balloon { get; set; }
        public virtual State State { get; set; }
    }
}
