//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BalloonsEntities : DbContext
    {
        public BalloonsEntities()
            : base("name=BalloonsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessories { get; set; }
        public virtual DbSet<Balloon> Balloons { get; set; }
        public virtual DbSet<BalloonStatu> BalloonStatus { get; set; }
        public virtual DbSet<BalloonType> BalloonTypes { get; set; }
        public virtual DbSet<Billing_Information> Billing_Information { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Distributor> Distributors { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Seasonal> Seasonals { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<State> States { get; set; }
    }
}
